name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"

env:
  ECR_REGISTRY: 115917394410.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO_DB: tienda-db
  EKS_NAMESPACE: tienda

jobs:
  build-push-deploy-db:
    name: Build, Push y Deploy DB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir tag de imagen
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build imagen DB y push a ECR
        run: |
          cd db
          docker build -t $ECR_REGISTRY/$ECR_REPO_DB:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO_DB:$IMAGE_TAG
          echo "✅ DB image pushed: $ECR_REGISTRY/$ECR_REPO_DB:$IMAGE_TAG"

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Conectar al cluster EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name tienda-eks
          echo "✅ Conectado a tienda-eks"

      - name: Deploy MySQL en EKS
        run: |
          kubectl apply -f k8s/mysql-secret.yaml -n $EKS_NAMESPACE
          kubectl apply -f k8s/mysql-deployment.yaml -n $EKS_NAMESPACE
          kubectl apply -f k8s/mysql-service.yaml -n $EKS_NAMESPACE
          echo "✅ MySQL secret y deployment aplicados"

      - name: Ver estado pods DB
        run: |
          kubectl get pods -n $EKS_NAMESPACE -l app=tienda-db
          kubectl get svc tienda-db -n $EKS_NAMESPACE
